version: "3.3"
services:

  db:
    image: postgres:12
    env_file:
      - ./backend/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432


  backend:
    image: 'book-app-backend'
    depends_on:
      - db
    env_file:
      - ./backend/.docker.env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: bash -c "poetry run python /backend/backend/initial_data.py && uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000


  frontend:
    image: 'book-app-frontend'
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    command: npm run serve
    ports:
      - 8080:8080
    